publish:
    cp -R _book/* /Users/silenceper/workspace/blog/silenceper.com/static/wechat/
    cd /Users/silenceper/workspace/blog/silenceper.com/
    HUGO_ENV=production hugo
    make publish
.PHONY: publish
